name: Make all the tests
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Clean the code
        run: make clean
      - name: Compile
        run: make
      - name: Run tests
        run: sh test.sh
